# Generated by Django 4.2 on 2023-04-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Telephone number",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Cinema number")),
                ("places", models.PositiveIntegerField(verbose_name="Places count")),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema.cinema",
                    ),
                ),
            ],
        ),
    ]
