# Generated by Django 3.2 on 2023-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Hall number'),
        ),
    ]
