# Generated by Django 3.2 on 2023-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_hall_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='places',
        ),
        migrations.AddField(
            model_name='hall',
            name='rows_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Rows count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Seats count'),
            preserve_default=False,
        ),
    ]
