# Generated by Django 3.2 on 2023-05-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_hall_number'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('places', models.PositiveIntegerField(verbose_name='Places')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall', verbose_name='Hall')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.ManyToManyField(to='session.PriceList', verbose_name='Price'),
        ),
    ]
