# Generated by Django 3.2 on 2023-05-09 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('middle_name', models.CharField(max_length=128, null=True, verbose_name='Middle Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('middle_name', models.CharField(max_length=128, null=True, verbose_name='Middle Name')),
                ('country', models.ManyToManyField(default=None, to='movie.Country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('middle_name', models.CharField(max_length=128, null=True, verbose_name='Middle Name')),
                ('country', models.ManyToManyField(default=None, to='movie.Country', verbose_name='Country')),
                ('language', models.ManyToManyField(default=None, to='movie.Language', verbose_name='Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating')),
                ('duration', models.PositiveIntegerField(help_text='Длительность фильма в секундах', verbose_name='Duration')),
                ('actor', models.ManyToManyField(default=None, to='movie.Actor', verbose_name='Actor')),
                ('country', models.ManyToManyField(default=None, to='movie.Country', verbose_name='Country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.director', verbose_name='Director')),
                ('genre', models.ManyToManyField(to='movie.Genre', verbose_name='Genre')),
                ('language', models.ManyToManyField(default=None, to='movie.Language', verbose_name='Language')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.producer', verbose_name='Producer')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie', verbose_name='Favorite Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='language',
            field=models.ManyToManyField(default=None, to='movie.Language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.ManyToManyField(default=None, to='movie.Language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ManyToManyField(default=None, to='movie.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='language',
            field=models.ManyToManyField(default=None, to='movie.Language', verbose_name='Language'),
        ),
    ]
