# Generated by Django 3.2 on 2023-05-18 18:34

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20230509_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.person_upload_to, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.person_upload_to, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.poster_upload_to, verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='producer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.person_upload_to, verbose_name='Photo'),
        ),
    ]
