# Generated by Django 3.2 on 2023-05-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20230514_1102'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.pricelist', verbose_name='Price'),
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
